# Generated by Django 4.2 on 2023-04-07 17:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=50)),
                ("types", models.CharField(max_length=500)),
                ("link", models.TextField()),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("is_split", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("area", "title", "pub_date")},
            },
        ),
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="GovDocWordFreqAggr",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("freq", models.IntegerField(default=0)),
                ("area", models.CharField(default="TOTAL", max_length=50)),
            ],
            options={
                "unique_together": {("word", "area")},
            },
        ),
        migrations.CreateModel(
            name="GovDocWordFreq",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("freq", models.IntegerField(default=0)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="datas.govdoc"
                    ),
                ),
            ],
            options={
                "unique_together": {("word", "record_id")},
            },
        ),
    ]
