# Generated by Django 4.2 on 2023-04-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="govdoc",
            name="area",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="is_split",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="link",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="govdoc",
            name="types",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="govdocwordfreqaggr",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
