# Generated by Django 4.2 on 2023-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0002_alter_govdoc_area_alter_govdoc_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="govdocwordfreq",
            name="word",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="govdocwordfreqaggr",
            name="word",
            field=models.CharField(max_length=500),
        ),
    ]
