# Generated by Django 4.2 on 2023-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0004_alter_govdocwordfreqaggr_id_alter_testmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
