# Generated by Django 4.2 on 2023-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0009_remove_weibodoc_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("op_time", models.DateTimeField()),
            ],
        ),
    ]
