# Generated by Django 4.2 on 2023-04-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0010_operations"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordHotness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=500)),
                ("year", models.IntegerField()),
                ("freq", models.IntegerField(default=0)),
                (
                    "datetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="datas.datatype"
                    ),
                ),
            ],
        ),
    ]
