# Generated by Django 4.2 on 2023-05-03 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0011_wordhotness"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toutiaodoc",
            old_name="context",
            new_name="content",
        ),
    ]
