# Generated by Django 4.2 on 2023-05-14 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datas", "0012_rename_context_toutiaodoc_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordhotness",
            old_name="datetype",
            new_name="datatype",
        ),
    ]
